<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $guarded = [];
    // protected $fillable = [
    //     'title',
    //     'excerpt',
    //     'body'
    // ];

    protected $with = ['category', 'author'];

    public function getRouteKeyName(){
        // return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
        return 'slug';
    }

    public function category() {
        return $this->belongsTo(Category::class);
    }

    public function author() { // attempt to author_id
        return $this->belongsTo(User::class, 'user_id');
    }
}
